### ISSUE TITLE
Attack/Defense bonus info - upgrade.

### ISSUE THREAD

**Issue by csrsc** [dsiekiera/foe-helfer-extension#1030]
Is it possible to add attack/defense to guild members like it works in neighbors  ?
It would be very helpful to help guild members... =)
![2020-05-14 10 01 48]
(https://user-images.githubusercontent.com/26833140/81908990-47dfc080-95ca-11ea-81b5-0d392437d9ac.png)

**Comment by andrgin** [comment]
Will be included in the next update.

**Comment by csrsc** [comment]
Great!!!
Thank you VERY MUCH =)

Regards,
CJ

sob., 16 maj 2020 o 20:59 Gindi4711 <notifications@github.com> napisał(a):

**Comment by osv** [comment]
@csrsc btw, you can view this right now not only for neighbors. Press F12 and type in console `UseReaderOnAllPlayers=1` and than visit friend or guild member

**Comment by csrsc** [comment]
Great, it really works =)
I don't know why, for now, but for some players the value is wrong (15%
less attack for attacking army / 15% less defense for defending army).
For me it show 15% more defense for defending army..
I will check it and let you know if i found something.
But now I see which players we need to help.
Thank You very much =)


CJ.


sob., 16 maj 2020 o 21:46 Olexandr Sydorchuk <notifications@github.com>
napisał(a):

**Comment by andrgin** [comment]
It clearly states "Estimated bonus" because there are some effects that we can not calculate.

For example:
Attack/defense bonus from the tavern or items
Boni from set buildings: Here we assume you have the full set positioned correctly
New effects that have not been implemented yet.

Minor differences are expected to occur, but it gives you a rough information what you could expectoffense/defense wise.

**Comment by csrsc** [comment]
Heh - exactly, that's what I was looking for...
Once again, thank U very much and have a nice Sunday =)

Regards,
CJ


niedz., 17 maj 2020 o 14:21 Gindi4711 <notifications@github.com> napisał(a):
