### ISSUE TITLE
Opening Gb window causes Fp stock to show 0 (on BETA server)

### ISSUE THREAD

**Issue by Tanmayl11** [dsiekiera/foe-helfer-extension#1044]
opening gb window on beta sever is making "Fp stock" to drop to 0, not sure if its happening on live servers.  https://prnt.sc/six4dq

**Comment by scibuff** [comment]
Are there any errors in the console (F12 > Console)?

**Comment by Tanmayl11** [comment]
![Screenshot_214](https://user-images.githubusercontent.com/65541014/82211704-ea7fa280-992e-11ea-80eb-351dfebe6501.png)
this

**Comment by andrgin** [comment]
This is a change on Innos side.

A few months ago the only ingame display for inventory FP was when opening great buildings and Inno transmitted the FP on stock when opening the GB.

With the new technology tree they introduced a new method. Instead of transmitting the stock FP the client is tracking FP packets in inventory on its own.

It seems that now Inno has changed to this method for great buildings as well. This means we will have change our method as well and track all inventory changes of FP packets.

**Comment by ikdoemee** [comment]
Live server has been updated. Issue is now also there

**Comment by ScriptAdel** [comment]
Sawe problem with me when i refresh page it gone
and every time i open a GB it goes down to Zero 0

**Comment by scibuff** [comment]
I started working on this (please see #1059) but then committed work-in-progress accidentally to an existing pull request so had to revert :(
