### ISSUE TITLE
Archeology event helper

### ISSUE THREAD

**Issue by saml1991** [dsiekiera/foe-helfer-extension#1054]
A good strategy is to use shovel when it reveals 4 or more shadows and dynamite when it reveals 5 or more shadows. 

Is it possible to add a box that shows a number next to brush, shovel and dynamite of how many shadows can be revealed using that tool. 

If brush can reveal >1 show as green, if shovel can reveal >4 show as green and dynamite >5 show as green. 

Thanks very much for the helper.

**Comment by andrgin** [comment]
Considering the work needed we do not want to make tools specific for one event.

The tool for spring event was different because the code of "select one of x animals/players/chests" etc. work on multiple events.

About which tool is the best there are more factors that should be considered:
.) How many unknown tiles can you clear with them
.) How many tiles can you make visible
.) How many items can you collect with them
.) Does it help you travelling further to the right
.) Is the way you are travelling to the right centered (means you will make more tiles visible in later rounds) or is it at the border/near a solid block.

**Comment by outoftheline** [comment]
As this is too specific for the reasons mentioned above, I'll close the issue.
