### ISSUE TITLE
Attack and defense

### ISSUE THREAD

**Issue by mcraebg** [dsiekiera/foe-helfer-extension#1132]
I think FoE Helper dont show A/D from disconected buildings from the road.

**Comment by andrgin** [comment]
Yes there is no offense/defense boost if the building has no street connection. The only effect that stays when disconnecting a building is population of houses.

**Comment by osv** [comment]
but this is not true for 2020 patrick set as minimum. I have disconnected Druid Willow and still have defend boost :)

**Comment by andrgin** [comment]
I just checked. Great buildings like Zeus or event bu8ldings like the pirate ship are all loosing their bonus. It seems to only apply to the set bonus of celtic forest and cherry garden, but those set boosts are just an estimate anyway because I cant check if a player has the full set and if it is positioned correctly. This is why the box say "estimated values". There are just some things I can not calculate or at least not with reasonable effort.

**Comment by mcraebg** [comment]
cherys,elephant and classical gardens dont need road and attack still exist
