### ISSUE TITLE
GBG overview popup

### ISSUE THREAD

**Issue by wolfiewolfgang** [dsiekiera/foe-helfer-extension#1186]
Please refrain from using any popups unless we opt into it.  Today the GBG overview stated poping up every time I log in.

**Comment by andrgin** [comment]
Having to opt in for every feature of the game would be a support catastrophy, because often used features might disappear after clearing cookies as the settings get wipe or after installing on a different PC. Every new feature must be on per default.

What we will try to do is include a setting to switch off new popups, if we think that it is annoying for some players.

**Comment by MilaPi** [comment]
So this is not a bug?? Closing popups every time I switch between my cities is so annoying. Please make it optional.

**Comment by symbion6** [comment]
Seriously, this is closed as "Will not be implemented". I do NOT participate in GBG, however I get the GBG popup in my face EVERYTIME I open FoE. That's extremely extremely annoying. AT LEAST make a setting to show it in the settings.

**Comment by outoftheline** [comment]
This is a "bug" that happens when you use power tools. Power tools is against game rules due to automation.
