### ISSUE TITLE
resetting helper after ccleaner

### ISSUE THREAD

**Issue by boeffie** [dsiekiera/foe-helfer-extension#1226]
after cleaning cache etc, the foehelper needs resetting on length, it also turns on the negotiation helper which I have standard inactive. it does not seem to affect other active/inactive settings.
Is there anything I have to remove in cleaner settings to stop this recurring?

**Comment by andrgin** [comment]
I dont know the settings for ccleaner, but it should be called something like "cookies and websitedata".

Just a personal advice:
Be careful with tools like ccleaner. If you know what you are doing and just need a shortcut for deleting temporary files etc. it is fine, but do not click every button you can find. I already had several PCs that needed a fresh windows install because my users thought fixing the "registry errors" would make the PC any faster. No it does not and in some cases it really breaks some software.

**Comment by boeffie** [comment]
I have never had a problem before, using it. I don't click all buttons I can find. It never has interfered with any programs. But I do not know if I have used it since starting to use foehelper, though it seems unlikely I haven't.
All GBG data from this session have disappeared too, so there definitely is something interfering with foehelper, and would like to know what.

**Comment by calandula155** [comment]
Bonjour, j'ai le même problème, je n'ai plus de stats CBG, EG, récompenses et historique JcL
J'utilise CCleaner qu'innogame recommande dans tous les mp lorsque l'on fait un billet de réclamation.
J'aimerais bien savoir que faire? Merci :))

**Comment by scibuff** [comment]
I'm sorry but we cannot possibly know all impacts of the use of CCleaner. It is quite likely it simply removes the stored data. As this is not an issue for thousands of users who don't use (in my opinion useless) 3rd party apps such as the CCleaner, if you experience data loss with CCleaner, my recommendation would be to simply stop using it or figure out a way to exclude the game data from being erased.

**Comment by franzalex** [comment]
Hello @scibuff 

This issue is not due to CCleaner (or other similar cleaning tools).  
It also happens when you manually clean up the browser data (e..g. ```CTRL+SHIFT+DEL``` in Chrome).  Cookies and site data are grouped under the same item so clearing cookies _automatically_ clears FoE Helper data too.

In my case, I stream TV with browser which causes my caches to increase very rapidly requiring I clean them regularly. Unfortunately, doing this regular clean up means that I *always* end up clearing the FoE Helper stats.

Is it possible that the data gets stored somewhere else, like how other browser extensions do it (e.g. uBlock, Tampermonkey) so that clearing cookies and caches does not clear the helper data? Thank you.
