### ISSUE TITLE
Possible to not update to newest version with every important function removed?

### ISSUE THREAD

**Issue by Myfoeuser** [dsiekiera/foe-helfer-extension#1266]
Like many other people I use the nego, gb cal and hidden incident almost exclusively. The tool is nice, and I appreciate the time you put into it  to create the other functions (I even donated via paypal), but it is worthless to me without it. 

Can I ignore the update and keep the old version running? Is it possible or forced update?

**Comment by andrgin** [comment]
1.) We do not support any previous versions or how to stop automatic updates. If most players decide to reject the update this might cause Inno to change their decision to tolerate the helper and they might change the rules so all browser extensions are forbidden.

2.) I suggest trying the new update. It is not as bad as it sounds:
.) Negotiation helper still works. It is only disabled for GBG, but in GBG there are not that many combinations that you really need it. You are a bit faster, but that is all. For those having trouble negotiation efficiently in GBG we might come up with a strategy guild specific for 5/6 good negotiations after analyzing the tables.
.) Hidden incident works as before. The only difference is that we do not show incidents that have not appeared yet, but seriously who needs that anyway? We included those events too because it was no work, but the important ones are those that are already here.

**Comment by Pilipen1923** [comment]
Добрый день. А почему убрали возможность просматривать при грабеже изготовленную продукцию? Возможно ли вернуть эту функцию и отказаться от других?

**Comment by andrgin** [comment]
This feature has been removed because Inno requested it:
https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper/44

**Comment by RubenLungu** [comment]
Can you let me know when did you all start removing these features so I know which commit to clone, please? I would like the latest version that still has all these features that were removed. I'm not planning on using it just yet but I just wanna have it. Thanks!

**Comment by scibuff** [comment]
We will most certainly no provide such details ... if we suspect people forking the old version and/or looking at the commit history, the relevant history might be cleared completely (branches into a private repo) ... so please dont

**Comment by andrgin** [comment]
We do not provide any support for using the old update.

**Comment by lukaszluczak** [comment]
I don't think anybody will fork it and provide public version with missing features and new toys.
