### ISSUE TITLE
Asked to "understand/understood" on every FOE "world" every time reloaded.

### ISSUE THREAD

**Issue by mcbluefire** [dsiekiera/foe-helfer-extension#1324]
I did not appreciate the update acceptance screen at all and am further annoyed with it asking for me to note I "understood" when I first load each world and cannot do anything in forge of empires until I accept..  Please know that the word "understand/understood" is a legal term in the US which means that I stand under you legally - so should not be used.  It is inappropriate to block playing the game until accepted - rather the extension should just not work until accepted with an "I acknowledge" as I am not entering into a legal agreement with you all.

Appreciate all your efforts on the extension, but I'm sure it's popularity will likely wane as a result of FOE's demands.  Ah, well. :)

**Comment by mcbluefire** [comment]
Correction, I have to accept the update every time I refresh any FOE tab.  Not good.

**Comment by andrgin** [comment]
1.) You choose to not read our statement and close the window any time. In this case it will come again on the next reload.

2.) If you confirm that you understood those changes the box will not come again next time. You have to do this for every world because every world has seperate settings/data.

3.) If you decide you refuse to read reasons for the update and dont want to have this window block your screen you can remove the extension from your browser.

**Comment by mcbluefire** [comment]
I have selected the check box and then clicked "understand" and yet it comes back after refresh on every "world".  I may very well just remove the extension, but honestly blocking access to the game is not very ethical for an extension - preventing the continuation of the extension is understandable and acceptable behavior if one doesn't want to acknowledge the updates.

**Comment by andrgin** [comment]
This message box is there so we do not get flooded with bug reports and players blame us for the removed features (many players still dont get it).

And no it does not appear more than once a world if you click the checkbox. I already tested that as long as you dont do things like clearing your cookies every time or surfing in privacy mode.
