### ISSUE TITLE
Change to Production Overview Happiness Efficiency

### ISSUE THREAD

**Issue by chip12** [dsiekiera/foe-helfer-extension#1396]
I'd suggest that the happiness efficiency should be expressed without the "polished" bias.   If I'm sorting for the purpose of determining which structures I want to sell/buy, the comparison needs to be using the same baseline.

Maybe there's a different reason for sorting and comparing based on current production, and if so, perhaps it would be good to have a checkbox to allow one to select whether efficiency value should or should not include its current polished value.

**Comment by andrgin** [comment]
I am aware of this problem, but I dont know how to solve it.

The same thing applies to all coin/supply/guild power productions as well and I dont want to have a different logic just for happiness.

For coins we have buildings like the shrines of knowledge, that produce FP as well so they will always be motivated in most cases. Then we have buildings like regular residential buildings that will not get motivated in  most cases so comparing them both unmotivated or both motivated will not make much sense. We can also not make this a a general rule because low players might get their residential buildings motivated as well, so showing the current seems the better choice.

When comparing event buildings it gets even more complex as buildings will start showing additional benefits when motivated (for example 30 goods of buildings era when motivated).
