### ISSUE TITLE
Statistics: incorrect drops to 0 for troop types

### ISSUE THREAD

**Issue by capshort** [dsiekiera/foe-helfer-extension#1522]
Hi,

I've stumbled upon the statistics showing strange drops to 0 for _all_ my troop types. Never knew why, wasn't too important since I knew it was an error. But now I know the reason, have a look at this (I've reduced the troops shown by filtering only the all ages units):

![Screenshot_20200718_191639](https://user-images.githubusercontent.com/25132855/87858156-2a153b80-c92c-11ea-9c3f-27b5302c0d37.png)

And then this:

![Screenshot_20200718_191451](https://user-images.githubusercontent.com/25132855/87858160-34cfd080-c92c-11ea-8040-a5074eb5d250.png)

Seems I have opened the ingame army overview that comes with the ancient egypt settlement and this somehow meddles with the statistics. It's not too nasty since I know it to be incorrect but it would of course be nice to have consistent statistics.

**Comment by andrgin** [comment]
Can you reproduce this issue with the current version?
The bug with the egypt settlement was fixed somewhere in May.

**Comment by andrgin** [comment]
I could reproduce this issue. This always happens when you visit the outpost, do a fight, return to the outpost and open the army overview again. The reason is that returning from battle is treated like returning to home village.
There will be a fix in the next uodate. Unfortunately existing data will stay this way.
