### ISSUE TITLE
ban every other day with FOE Helfer

### ISSUE THREAD

**Issue by stonekhold** [dsiekiera/foe-helfer-extension#1564]
Thank you for contacting the Forge of Empires Team.

We are sorry to hear, that you have experienced a ban in our game. Unfortunately our system detected that you were using a third party program or plugin that is not allowed to be used in our game.

In order to make sure our detection for third party programs and plugins stays accurate in the future as well, we can't give you any details about the way we have detected you or which program you have been using.

Please be informed, that any program/plugin that automates processes in our game or gives you an unfair advantage over other players is considered as 'not allowed'. InnoGames has not officially allowed the usage of any third party program or plugin.

In order to avoid any further sanctions we strongly recommend removing any third party program and plugin that could influence our game. Please review your browser extension for any add-ons. In some cases it may also help to re-install the browser again. Thank you for your understanding.

Should you have any further questions regarding this matter, please let us know.

Kind regards,

Mimir
Co-Community Manager

**Comment by andrgin** [comment]
Bans are caused by the extension "Foe Powertools". There are no bans for Foe helper.

Inno has not officially allowed Foe helper because they dont want to be responsible if we add features that violate game rules. I guess this was a suggestion coming from their legal department.

For their statement:
Please be informed, that any program/plugin that automates processes in our game or gives you an unfair advantage over other players is considered as 'not allowed'

Foe helper does not automate any ingame actions. Also Inno has provided us with a list of features that have been falling into the category "unfair advantage" according to their recent definition. We have changed all those features 2 months ago.

Powertools on the other hand did automation of data gathering and they provided an unfair advantage so players using that extension have been banned.

**Comment by stonekhold** [comment]
Dont even know what power tools does and dont know how it got on my system, but I removed.
