### ISSUE TITLE
Motivation helper small improvements

### ISSUE THREAD

**Issue by belikoviv** [dsiekiera/foe-helfer-extension#1652]
Hi.

Cool! The second great tool (after GB calculators).
But needs some additions.
1. Urgently need possibility to copy player name from table.
2. Need some mark to understand from which time mark data from Town hall transmitted to Helper. As it was for motivation statistics on your site.
3. Many players pay attention not only on motivation/polish activity of friends, but on tavern activity also. So table need to have selections which activity to check: tavern, motivation/polish or both.

Thanks for your work - it excellent!

**Comment by andrgin** [comment]
1.) Why do you need to copy player name?

2.) We will include a message how many new events have been found when scrolling through the townhall. In the tool itself we will include a notification that you this tool only works with enough data from the town hall.
I dont know if this will be in the next update yet because the next update will be planned rather soon because we need to find a solution to the next sidebar of the game (that we currently would overlap when there are too many events).
Unfortunately there is no easy way to check if there are parts of data missing.

3.) Currently all player related events are shown in the overview. This includes:
a) Motivating/Polishing
b) Tavern visits
c) Attacks
d) Plunders
e) Accepted trades
f) Great building event (like new GB was built or if you get a reward from a finished GB)

This has already been implemented in the beta branch and will be included in the next update.

**Comment by belikoviv** [comment]
1. F.e. to write in guild which members are not motivate/polish me.

2.
> We will include a message how many new events have been found when scrolling through the townhall.
It was when data was transmitted to site database.
It will be enough in new release.

3.
> This has already been implemented in the beta branch
I hope that all events are selectable so I may select only needed events in different cases.
>
