### ISSUE TITLE
Feature request: street count

### ISSUE THREAD

**Issue by DanChaltiel** [dsiekiera/foe-helfer-extension#1659]
Hi,

While trying to get the perfect city, I extensively use the city map widget to plan my building locations.

Lately, I came to an obvious conclusion: the less street I have, the more optimized is my city.

Therefore, I would find it very helpful to have the **percentage of my city used by streets**, beneath the "total area" and "free area" counts.

Actually, if this is not too much work, it would be awesome to have the percentage and number of tiles of all building types, with maybe a pie chart and a bar chart.

**Comment by DanChaltiel** [comment]
Here is what I'm proposing in my PR:

![image](https://user-images.githubusercontent.com/15105152/101391724-08115b00-38c5-11eb-955f-a8d1af79f5d9.png)

**Comment by andrgin** [comment]
1.) I dont think that area covered by streets is a good indicator how efficient your city layout is.
Lets say you have 10 5x5 production buildings needing a single road. If you do it efficiently you need about 250 tiles + 25 roads equals 275 total.
Now you redesign your city and replace those with 8 5x5 buildings of the next era that give the same production, but need 2x2 roads.
You will need 200 tiles + 40 tiles for roads equals 240 tiles.

So you have saved 35 tiles while needing 15 more tiles for roads than before.

2.) The percentages listed on the right looks good, but I am not sure if we can do this because most event buildings are classified as either residential building or production building as well even when their main purpose is generating FP, goods and attack/defense boni.

**Comment by DanChaltiel** [comment]
1) Well of course it should have been understood as "efficient, given a certain level". You can obviously make your city more efficient by using better buildings. But with the same buildings, you can arrange them in a way that uses more or fewer streets. For instance, if you have 4 5x3 (cols x row) buildings, arranging them in columns would require 4x5=20 streets while arranging them in rows would require only 4*3=12 streets. You can thus earn 8 tiles which can sometimes be very valuable!
I recently earned 4 tiles by moving a GM. This is especially useful when, like myself, you were not the wisest person when you chose which tile to unlock...

2) I agree, but couldn't we say the same about the colors then? Indeed, event buildings are quite multicolored, but I still find the map very valuable. Percentages are just a numeric transcription of those colors.

**Comment by JhonnyBn** [comment]
Very nice update! But I think the translations are missing and there's some extra <br>'s

**Comment by andrgin** [comment]
I have added translations for German and English. Other languages can be done with http://i18n.foe-helper.com
