### ISSUE TITLE
Menu bar unusable 

### ISSUE THREAD

**Issue by WelverinXarann** [dsiekiera/foe-helfer-extension#1665]
The new change that moved the menu bar to the bottom leaves the left and right arrows visible only unless the browser is in full screen mode making it unusable under normal use circumstances. Not all of us play that way and I've made the suggestion before to allow players to self dock the bar. That way if they want it on top, side or bottom, a bit to the left or a bit to the right is all an option. Hard locking it in a set place will always be a limitation. Additionally, being able to resize windows like for city overview would be a welcome feature that goes back to the "not everyone plays full screen mode" statement. I have 2 worlds open side by side and to use the new button layout that becomes impossible to do leaving either 2 open or only 1 visible at a time with menu use.
Attached is the new and "improved" location that's hidden from view and unusable. Marked up some options for hard lock locations or where i'd personally move the bar if there was the option to do so. The memory lock can work the same way as the button location setup where it's lockable by personal preference. Most cad toolbars are lockable like that cause of how vastly users are different.  Bottom corner dock going up would work also as the length of the bar can be set to fit. 

![Screenshot 2020-12-08 203714](https://user-images.githubusercontent.com/60704990/101562322-35c5d500-3995-11eb-952c-c4951293d0cf.png)

**Comment by ndjv2739** [comment]
Agree! Please either move it back where it was (along the right side) or make the position user-selectable.

**Comment by Th3C0D3R** [comment]
the thing about the right side is that Inno is going to make the icon bar dynamicaly and so it will be behind the foe-helper menu if its too long. leftside also dies not work because there will be the "Building" Menu fomr the game. also at the top because there is the chat. we will discuss about a possible solution

**Comment by comm1968** [comment]
Ereignisse im Wasser werden u.U. verdeckt...

**Comment by dsiekiera** [comment]
> Agree! Please either move it back where it was (along the right side) or make the position user-selectable.

We only had 3 days to move the bar. Inno does not write to us when it is installing something new. We are already working on new versions. 
So stay calm and wait!

**Comment by dsiekiera** [comment]
@WelverinXarann 
Your playing style on a 4k monitor is no match for nearly 100k other players. Especially not the positions you show. Over 90% of all players have a "normal" large screen on which your suggestions don't even fit.
Play fullscreen for a few days and wait and see.

**Comment by outoftheline** [comment]
@WelverinXarann 
Your first suggestion wouldn't work with the Build menu, the GvG log or the GBG log.
Second one is difficult when using the chat.

We're looking into alternatives, but it's not as easy as you make it look.

**Comment by quark-z** [comment]
I suggest that the Settings option (to configure helper bar) be made the first box by default this allows the user to configure the number of boxes to appear so make the right-hand-side arrow visible whatever their display size.

**Comment by WelverinXarann** [comment]
Again, making the bar placement be user selectable and rotateable (if possible) would give everyone an option to place it where it fits their personal style of play, monitor layout etc.  Obviously relocating it is possible since it was done. It was also rotated from it's original orientation. Giving the option for where to rotate it and where to lock it shouldn't be TOO difficult since most of the coding for the windows and window behavior is already done. Assuming that everyone uses the same layout at all times is a stretch for everyone honestly. I'm running 2560x1600 resolution and going full screen with it becomes a massive eyestrain for the brightness and colors as well as limiting how i play the game. 

The build bar isn't one that's open at all times for 95% of people. The duration it's open shouldn't impact the helper's functionality any more then it's current location does for finding incidents. The chat box location again is subjective as many people don't use the chat system. Lower left corner going up can be configured for a line of boxes reaching up to the new dynamic bar they have coming down. 

Again, i was giving options knowing that there are many many styles of play and convenience and in most cases no 2 will be the same. Ideal would be to let the players choose where to dock the bar and in which orientation.  If default locations need to be used for it then the option to pick which and to rotate accordingly may be more doable. 

This is said by someone who is not a programmer but has seen such convenience options implemented in many things. My hope is that there's a way to do it without making it's functionality be suddenly limited by someone's screen orientation or use.

**Comment by andrgin** [comment]
1.) The current menu does support changing horizontal/vertical orientation. Switching from horizontal to vertical layout took us about 2-3 days as there are several things that must be tweaked manually like auto size depending on screen width/height, drag and drop behaviour, tooltip positions and so on. I dont want to say that it is not possible, but not in the few days we had.

2.) We had a discussion which resolutions we still want to support and we decided on a minimum resolution of 1280x768 at a zoom factor of 100% as this includes older 1280x1024 monitors as well as cheaper 1366x768 displays typically used in low end notebooks. Our target for this resolution is having at least 4 buttons visible in the menu as we have experienced that 4 buttons are enough to cover the most used functions.

Here is a screenshot of how the menu looks at 1280x768:
![Screen](https://user-images.githubusercontent.com/55417498/101670695-c8c54480-3a53-11eb-8ebb-0c7869abab04.png)

The Inno bar on the right is not the maximum size. In my case I could still get an additional button for lighthouse of Alexandria. Also there could be icons for special offers in the shop, if buildings get plundered or limited boni for great buildings I do not have. We do not know what the maximum number is, but I suspect that it can reach the bottom which could already be problematic. We will see if this is an issue.

.) As you can clearly see adding the bar to the right is not an option any more as we would overlap existing bar even blocking the scroll down button.
.) Adding the menu on the left side is also not an option space is already very low with the permanent quest icons, but also it will block a lot of temporary content like the icon for 5 diamond collect all option, build menu, plunder menu (when visiting players) etc.
.) Adding the menu left of the Inno bar in a second column is also a problem because it will cover the chat

For players that are playing at a resolution of less than 1280x768 (or have 2 windows open at the same time) I suggest a smaller zoom factor of the browser (Ctrl + mouse wheel). For example if you have only 960 pixels width (1920x1080 with 2 windows nearby) you need to set the zoom factor to about 75%.

**Comment by WelverinXarann** [comment]
Does that mean that we'll be given the option to orient it for our use via settings? 
I can understand why the layout was done that way for small screens and resolutions. I'm not asking for it to be reset cause with the new menu it makes sense to move it. I'm asking if it would be an option to manually rotate it even in it's current location.  From what i can tell it's locked in place via the friend/hood lineup as opposed to the left side of the window. (not sure if that's a valid locking point obviously)
Again, without a ton of explanations for why it was done as it was since that makes sense for small screens and such, my question still is wether or not it's a possible option for user lock or floating and flippable toolbar. In essence, that wouldn't cause a change for those who are forced into using it as is but would give those with better gear the option to make more convenient layout use of the functions.  If it's not possible then fine. If it is then please and thank you. 
There's no point re-explaining the obvious regarding weaker gear when the question doesn't regard that. Question has regarded the options for better functionality on better gear and a floating bar that offers 90 degree rotation via settings would do that and leave things fully usable for all involved. The other boxes opened are all floating and can be moved to where it's most easily usable, most convenient and so on. Would be great if the toolbar itself had the same option.

**Comment by WelverinXarann** [comment]
Fair enough.  I'll keep my eyes open for what those are and give thanks in advance for looking into them.

**Comment by SkateScout** [comment]
I would also prefer that the bar orientation/placement is on user Choice. Even an second column on the right would be greater than on the bottom because most resolution have more width than height.  You said that "Switching from horizontal to vertical layout took us about 2-3 days" so the switch is in the svn documented and it should take less time to make it an user choice than the initial change.

**Comment by Th3C0D3R** [comment]
![grafik](https://user-images.githubusercontent.com/7798500/101772146-44260500-3aeb-11eb-894c-bebe0517bb64.png)

does this make you all happy?

**Comment by WelverinXarann** [comment]
Awesome! One on the left works perfectly for me.  lol

**Comment by belikoviv** [comment]
> does this make you all happy?

Almost all :)

I want to offer one more variant:

![2012112154](https://user-images.githubusercontent.com/35531243/101949347-24323680-3bfc-11eb-95d9-68b89142ff15.png)

With button to hide/show menubar like social panel.

**Comment by nev00** [comment]
adding a vote for the - hide/show menubar option
this way it can just be minimized if its overlapping something on the smaller screen, and doesn't hide incidents when searching for them during events :)
