### ISSUE TITLE
Incorrect number of turns used to solve complex negotiation

### ISSUE THREAD

**Issue by hajiboy** [dsiekiera/foe-helfer-extension#1879]
The foe helper is trying to incorrectly solve a 3-turn complex negotiation using 4 turns. Today's St. Patrick's event daily task has a complex negotiation that only allows 3 turns. I asked the administrators whether this is correct and they said yes, there are no rules on how many turns complex negotiations get and that 3, as ridiculous as it sounds, is correct.

However, foe helper is trying to solve this complex negotiation using 4 turns, so even when it tells me it's 100% guaranteed to solve the negotiation, it fails 1 turn short.

https://ibb.co/hYpztgw

**Comment by andrgin** [comment]
Unfortunately we do not get the information if there are 3 or 4 turns on a 8 round negotiation except for GE where it is based on the tavern boost so we can only asume it will be 4.
We classify 3 rounds for 8 goods as a bug by Inno because there is no way of solving it with a reasonable success rate.

**Comment by andrgin** [comment]
Update: I have found the information for the number of turns. It was hidden in the resource list. ResourceStock['negotiation_game_turn'] should give the number of turns if read at negotiation start.

**Comment by andrgin** [comment]
Will be fixed in the next update
