### ISSUE TITLE
Carthage not available

### ISSUE THREAD

**Issue by JohnKleb** [dsiekiera/foe-helfer-extension#2183]
Cannot submit nor see my world Carthage.  The submit box in the game does not react and when I try to see the city in FOE-Helper it appears as a small thin line and when clicked on it says "this page isn't working".  I have attached a couple of images.

![This page isn't working](https://user-images.githubusercontent.com/13572588/137323067-06499c64-d080-4239-aad7-093c6ba6f57d.png)
![City Selector](https://user-images.githubusercontent.com/13572588/137323070-c4d2b11d-9df2-43ae-8407-be69fcee9e04.png)

**Comment by JohnKleb** [comment]
Any progress with this?

**Comment by Cady36** [comment]
I'm wondering about this as well. We have some newbies on Carthage who desperately need me to redesign their cities. lol.

**Comment by JohnKleb** [comment]
I wish we could at least get a "Issue received, we are working on it"

**Comment by Parama91** [comment]
Well.. its not that easy to say "we are working on it", because we dont have a regular timeframe when we develop on the helper and if we are working on it, its mostly done within one session. So sending an "we are working on it" would be irrelevant when the bug is fixed after 2 hours, and if he is fixed you can see it on the GitHub issue as labeled "next release". Also "issue recieved" is in my opinion nothing relevant, because we recieve the issue when you create it here on GitHub.

But you can try to ask on Discord with the @Developer Tag and if someone has time to check or even solve the problem you will get an answer. ;)

**Comment by JohnKleb** [comment]
Wonderful response Roman.  Completely understood.  We appreciate what you have built and FOE would be much less enjoyable without your efforts.  You guys have built a beautiful tool.

**Comment by JohnKleb** [comment]
Thanks Roman.  I had a devil of a time with Discord as I was not set up and
a gremlin captured me on my way in.  That said.  And not knowing Discord.
How do I find FOE Helper there?

//John  +1.630.935.2127

**Comment by Cady36** [comment]
@JohnKleb In the Helper, choose Settings then Help. There's a Discord link there. :)

**Comment by Cady36** [comment]
This headline should be updated to "US28 not available in city planner". (US 28 being "Carthage".) From talking to Mainline on Discord, it needs to be added to the database.
