### ISSUE TITLE
Anzeige Rest-FP aktive Schleifenquest fehlerhaft

### ISSUE THREAD

**Issue by krupp58** [dsiekiera/foe-helfer-extension#465]
Die Anzeige der verbleinenden FP zur FP-Schleifenquest ist falsch. Anscheinend werden der erste Beitrag von einem FP und der erste von zehn FP nicht berücksichtigt. Nutzt man 1 FP nachdem 10 FP gesetzt wurden, werden die 10 FP nachträglich berücksichtigt, es bleibt aber eine Differenz von einem FP zum korrekten Wert.

**Comment by andrgin** [comment]
Ja da fehlt noch ein zusätzliches Refresh

**Comment by ljettinger** [comment]
I'm not sure exactly what Krupp is talking about, and i haven't seen it show the wrong amount except because it hadn't refreshed to the new amount after adding some... Originally it would refresh to the new amount required as soon as any FP were added at all and the total changed without needing to reload a new GB or anything... So hopefully that's what you're seeing 😊😉
