### ISSUE TITLE
Profit from snipping summary - an idea

### ISSUE THREAD

**Issue by MilaPi** [dsiekiera/foe-helfer-extension#475]
I've been wondering how much I profit from sniping. I would love to be able to see some summary within the addon, for example how much pr I earned from sniping weekly or monthly. I suppose the simplest formula would be "(friendly invest) minus (sniping invest)" once the particular level of the great building is closed.
PS. Sorry for no label, not sure how to do it.

**Comment by ljettinger** [comment]
Can't that amount be found by subtracting the two summed numbers on the investment sheet?? Because that's how I've been doing it... 
![image_2](https://user-images.githubusercontent.com/18238040/73210495-68b60000-4118-11ea-9f7c-d54723832df5.png)
Or is that incorrect?? I know it's not showing a historical value (which would be very helpful) and only FP currently in play, but I was wanting to ask what exactly those figures are anyway...
