### ISSUE TITLE
Fake incidents

### ISSUE THREAD

**Issue by 1msummers** [dsiekiera/foe-helfer-extension#516]
I am constantly being told that there are 3 "small road" incidents, yet none are found on any road. Not only that but the alert doesn't expire - it just stays there. This is definitely a bug.

If you invoke FOE's build mode, and then shove all buildings and roads into the save buffer, you can see the undeveloped field for your city. In that field, I can see 3 items (a fallen tree, a bush, and another smaller tree) all of which are made visible (in the normal display) by lifting buildings from the location of the buggy incident. None of them are actually on roads, although FOE Helper reports them as being "small road" incidents (as mentioned above, they are all actually UNDER other buildings). All 3 of my "small road" incidents persist from one day to the next. I have asked Inno about these "incidents" and they claim that they are just background decorations.

How can I get rid of them?

**Comment by Th3C0D3R** [comment]
Its definitely not a bug.
If the incident data says its on a road than it is on a road. There is no bug. Your perspective is just odd and you think after putting all Buldings into the save slot that the incident is on ground.

You have to blame Inno for coding it like this so that road incidents are displayed on ground

Just reload the city and the incidents will get a new place.

Close due to not being a bug from our end!
