### ISSUE TITLE
Feature Request - Battle Assistant

### ISSUE THREAD

**Issue by neooblaster** [dsiekiera/foe-helfer-extension#683]
Hi Team,

You made a **WONDERFULL** job. I tried to make similare tool to take notes and share event quests but I stopped due to missing time and then I found your tool.

Today, I come to you with an idea. Your **Negociation** tool is one of the most important functionality (from my stand point).
I would like to suggest the "Battle Assistant".

With the Field of Battle, actually, in a Excel file, I store all units combinations VS opponents to identify which is the best.

Hereafter, an sample to illustrate :

* `L` = Light Unit
* `H` = Heavy Unit
* `K` = Knight Unit
* `R` = Ranged Unit
* `S` = Siege Unit
* `V` = Thug Unit (Voyou in french)
* `C` = Champion Unit

I tried different combination versus a opponent group and I store the result of the battle (including their bonus)

![image](https://user-images.githubusercontent.com/22078558/77520893-2a239400-6e82-11ea-8b36-938dca1d9a00.png)

I Know you collect data to make statistics to increase data accuracy.
I suppose, it's possible to make a tool to suggest your unit combination to fight your opponent.

What do you think ?

Kindly Regards,
Nicolas D.

**Comment by andrgin** [comment]
The problem is that battles are far more complex especially in later ages:
1.) You cant say things like "heavy beats light" because at later ages it is often the other way round.
2.) You have lots of different abilities like being hidden in certain terrain or flying units that are immune to artillery or units that are fast enough to hit the opponent on he base line etc.
3.) many strategies heavily depend on attack bonus. With 300% attack bonus it is often better to take much artillery and kill opponents before they come close no matter which unit. If you dont have attack boni it does not work so well.
4.) Some strategies only work when played manually because AI will do a lot wrong.

**Comment by neooblaster** [comment]
Hi Andrgin,

Thanks for your reply.

I also note the same combination could be produce differents results (whereas opponent bonus were lower than the previous fight)
That why I thought about stastics. If each battle are recorded (combination, era, bonus) maybe we can identify a trend, which no reflect the trust, but the best solution against these opponent.
Depending of amount of data regarding one player (Bonus & Era), system use the closest solution founded. It's better than nothing.

Kindly Regards
Nicolas D

**Comment by andrgin** [comment]
No player will put an army that does not work at all or has many losses.
The results will very from no loss to 2-3 losses in most cases which is the difference I am getting for the same army with the same boni just based on terrain alone.
Also we dont know at all how good the attack was. Could have been an auto battle or could have been a good attack strategy.

**Comment by lnplnp** [comment]
I think you may consider the auto battle only...
And may be, you could only make a suggestion for the low era in a first version...

**Comment by outoftheline** [comment]
This topic is really too complex for a decent way to build a tool.
