### ISSUE TITLE
Feature refinement/request

### ISSUE THREAD

**Issue by Pendulous** [dsiekiera/foe-helfer-extension#775]
The player overview box that pops up when viewing member activity in Guild Battlegrounds would be more beneficial if a)the snapshot it takes of member activity happened regularly, and b) if previous snapshots could be viewed.  At present, it appears to be random- sometimes the snapshot will be 15+ hours past, other times much more recent.  Having this be a regular time (hourly or less would be great!) would be beneficial to leaders, particularly if the previous snapshots could also be viewed.

En export feature would be even better-  if the snapshot could be exported as a csv file (member, negotiations, fights, timestamp)  that would be the best!

Thanks very much for all you have done/ continue to do with the extension.

**Comment by timmep90** [comment]
> The player overview box that pops up when viewing member activity in Guild Battlegrounds would be more beneficial if a)the snapshot it takes of member activity happened regularly, and b) if previous snapshots could be viewed. At present, it appears to be random- sometimes the snapshot will be 15+ hours past, other times much more recent. Having this be a regular time (hourly or less would be great!) would be beneficial to leaders, particularly if the previous snapshots could also be viewed.
>
> En export feature would be even better- if the snapshot could be exported as a csv file (member, negotiations, fights, timestamp) that would be the best!
> 
> Thanks very much for all you have done/ continue to do with the extension.

Regarding a: Unfortunately there is no way to  take a snapshot regularly. Since this information can only be seen whenever someone visits the member overview, it's impossible to implement any function within the InnoGames ToS.
Other possible solutions require the usage of foe-helfer extension for every guild member (sync). But usually this shouldn't be expected.

**Comment by scibuff** [comment]
One option would be to give as an option to take a snapshot when we choose, rather than having one automatically taken when the box is open. 

As far as I know, something long the lines of csv export for several data boxes is already in the planning (if not already being coded). Maybe an easier option would a button to disable styling, so that the tables are plain text which one can copy and paste (e.g. into excel)

I myself wrote something like that back in January. 
![image](https://user-images.githubusercontent.com/722049/78912789-50ebe800-7a88-11ea-9ad7-b66f1a7f0ad4.png)

I'm currently finishing another feature but once done, if there's no csv export implemented by then, I'll add at least some copy data (into clipboard) option .

**Comment by Pendulous** [comment]
But it does not appear to do it with EVERY visit, only some of them.  I could easily log in once an hour to do comparisons, but without storage of the previous ones that is of little use.  Could each one go into a tab, perhaps?  saving the3 most recent, or similar?

**Comment by Pendulous** [comment]
Sorry, scibuff, I had not refreshed and didn't see your post...  I agree the button to disable styling would accomplish what I am after.  You have done that successfully?  I'd be thrilled if you shared it.

**Comment by osv** [comment]
@Pendulous Hi, Battleground snapshots can be exported to CSV in next release, https://github.com/dsiekiera/foe-helfer-extension/pull/829

**Comment by Pendulous** [comment]
when will this update be released?

**Comment by outoftheline** [comment]
an export feature has been implemented
