### ISSUE TITLE
Neue Idee - Investierte FP Archiv

### ISSUE THREAD

**Issue by urzytkowy** [dsiekiera/foe-helfer-extension#813]
Hallo zusammen,

ich habe erneut festgestellt, dass meine Gesamtanzahl an FP's (Lager + Umlauf + Gewinn) im Investitionsbereich stark gesungen ist. Leider ist eine suche nach dem LG und Platz wo man überboten wurde, sehr mühsam. Wäre es vielleicht möglich ein klein Tool (Übersicht) zu implementieren, dank den es möglich wäre auch bereits gelevelte LG´s zu sehen mit dem vermerk wie viel FP`s gewinn bzw. Verlust gemacht wurde? So könnte man schnell das LG´s finden wo man überboten wurde.

P.S. Ihr macht echt einen coolen Job!

Viele Grüße

Urzy

**Comment by Trajan522** [comment]
Hallo,

ich möchte mich meinem Vorredner anschließen. Wobei ich da ein anderes Problem ausgemacht habe und es vielleicht möglich ist, auch da ein Feature zu erstellen.
Hierbei geht es darum, dass ich feststellen musste, dass aus der Nachbarschaft während der 2 Wochen einige Nachbarn verschwinden. Ich gehe davon aus, dass diese Charaktere gelöscht wurden. Die dann dort investierten FP sind somit auch verschwunden. 

Könnte man diese "Person(en)" nicht irgendwie markieren, wenn die Welt gelöscht wird und 14 Tage später definitiv verschwinden? Teilweise könnten dadurch, je nach Investitionsvolumen, mehrere 100 oder 1000 FP betroffen sein und man kann dementsprechend reagieren.   

Danke für eure Arbeit und großartiger Job, den ihr macht.

Grüße

Trajan522

**Comment by scibuff** [comment]
Re: Urzy, the only way would be to keep track of all your investments in, let's call it, "investment archive" which would show (for example) the user name, building, level, how much you invested, what the expected return was, etc. 

But there is no automated way to check and compare the archive data with what's happened. The only way would be for you to visit the building, open it at the required level and see [that is the only time the building data is provided].

But you can already see all level events in the event history, so I'm not sure how useful this would be
![image](https://user-images.githubusercontent.com/722049/79474024-3379c980-8006-11ea-8316-acdccdfefbe5.png)

The best solution, by far, is to lock your position when you invent. That way you always know what you'll be getting back ...

**Comment by urzytkowy** [comment]
Re: scibuff, thank you for feedback. The problem is, that when you would like to find a reason for your "missing" FP's you have to check all (ini your case 15 Pages - in my "only" 14) pges with the GB's and count the points. I'm not sure if the deleted GB's are on the list, like ghost wrot it in his post. In a overwiev, you will be able to see everything direct, all GB's, invested FP's and win/lose of FP's - it would make the life easier ;-)

**Comment by scibuff** [comment]
OK, let's say you invest in a GB and we have a feature that will list that investment. Let's say the user deletes his account. The only thing the plugin could do (in theory) is to say that the user was in your neighborhood/guild/friend list and now he/she is not (anymore). 

Another scenario: let's say you invest in a GB, you don't lock your spot, and someone overtakes you (which has the effect that you lose FPs). The only way this plugin would know about it is if you revisit that same GB. That's the only time the plugin gets the GB data. The plugin does not and cannot make data requests to the FoE servers. It only "listens" to the data the servers send to the game and displays that data in a "better" way.

So if there was a list of your investments, there is no way to check how many FPs you actually got back when the building was leveled (until you visit the building). So you would still have to click through 14 pages and every single one of the buildings to find out.

**Comment by urzytkowy** [comment]
It's true, but there is another part. Thank such list, I could see, in case where I'm missing 1.000 FP, in which GB I invest a lot of FP and could save a lot of time instead to check those 14 pages and click to previos levels. Such feature save a lot of time in my opinion.

**Comment by andrgin** [comment]
1.) What we have available as data is:
.) The current investments in TH: All pages are transmitted at once.
.) The events: Obly the events per page.
.) The exact places when you open a single GB and scroll the levels

Investment list does not help here. We can tell if a GB is gone from the list but at that time we do not know if it was leveled or not
Event list does not help either because we dont know the invested or rewarded FP without opening every GB.

For investing:
.) Never snipe a GB if the place is not locked. Use the cost calculator to see how much you need to invest or if your place is locked.
.) Do not invest into inactive players. Even if they dont delete their account you will not get FP back and after a neighborhood change it is hard to find someone investing in their GBs. One sign of inactive players is that they do not have a guild (guild name is shown in cost calculator as well). I also try avoiding GBs without a bigger investment of the owner or a 1.9 investment of another player.
.) If you visit all neighbor GBs daily: If there was no neighborhood change an orange line in the cost calculator overview means there was an investment in this GB the last day. Green lines mean there was no investment since yesterday.

One thing to note for the investment overview:
In the investments overview there is no way to determine if a place is safe, but there are some investments where the extension can determine that the place is NOT safe (when there are more FP missing than your investment). If this is the case profit is capped at 0 for this GB.

Example:
You invest 100 FP in a GB that needs 1000FP to level up, reward for P1 is 300 FP. In this case only 100 FP are counted to the total sum of stock + investment + profit.
2 other players invest 150 FP each taking P1 and P2. Your reward is only 50 FP (less than investment). In this case 50 FP are counted.

**Comment by urzytkowy** [comment]
Ok, I see now that's quite complicated. Thank you any way for the answear! Have a nice evening :)
