### ISSUE TITLE
Negociation helper/advisor

### ISSUE THREAD

**Issue by Dlonrab** [dsiekiera/foe-helfer-extension#893]
Better is to follow statistics. 

If item-2 alleady filled 2 green slots , and another item-1 only filled one green slot,

and both are the last remaining options the fill the last available open slot , 

the odds for the right choice is greatly in favour for the item-1 because this item was uptill now only used once and item-2 was already used two times.

Choosing item-2 for a third time is less likely because the slots weree fairly randomly assigned by foe to a certain item.

kind regards 

A

**Comment by andrgin** [comment]
I will use an example to see if I understand your question:
You have 4 goods 3 rounds

Guess1: G1 G2 G3 G4 G1
Result: Green Green Red Red Green

So after 1st round there is only Good 1/2 and Place 3/4 left.
There are 4 possible solutions:
a) G1 G2 G1 G1 G1
b) G1 G2 G1 G2 G1
c) G1 G2 G2 G1 G1
d) G1 G2 G2 G2 G1

So on P3: Chance of G1 is 50% (2 of 4) and G2 is 50% (2 of 4)
On P4 it is the same.

I do not get your logic why the chance of using one good should be higher only because it was apready used more often on other non places.

**Comment by civwizzard** [comment]
Please can you add switch on off for this part of app/addon in settings.
I would like to use some of addon, but i do not use other sub apps and it is annoying or hard to close popup window every time....when i negotiate for example...

**Comment by andrgin** [comment]
You can already disable the negotiation helper in settings
